# Profile section
profile:
  first_name: Lydia
  last_name: A
  picture: static/img/user.png
  contact:
    address_one: 92170 Vanves
    address_two:
    phone: (+33)
  email: name@gmail.com
  description: Autonomous, always eager to learn and passionate to solve business challenge using data science, I thrive in building valuable data products and designing innovative solution for various business use cases


# Social section
social:
  github: https://github.com/lydiahiba
  linkedin: https://#


experience:
  item0:
    position: Finance Analyste
    company: KPMG
    from: fevrier 2019
    to: juillets 2019
    description: >
    Missions accomplished: Benchmark of target companies for a potential buyer, Account analysis, Realization of Teasers,Consolidation of Databook
    
  item1:
    position: Tax consultant
    company: PwC
    from: Décembre 2017
    to: juillets 2018
    description: >
    Missions accomplished: G50 review,Tax package review, Research work for memorandum
  


# Education section
education:
  item1:
    institution: Ecole IA Microsoft powered by Simplon
    program: Developpeuse Data & IA
    description: Apprentissage des différentes technologies autour de la Data et de l'Intelligence Artificielle, Machine Learning, Deep Learning.
    from: Mars 2020
    to: Novembre 2021
  item2:
    institution: Jedha Bootcamp
    program: Fullstack Data Science 
    description: Formation intensive autour des fondamentaux de la data science afin de crée son propre mdele de machine learning.
    from: septembre 2019
    to: fevrier 2020
  item3:
    institution: Universite de Lille II
    program: Master Finance & Banques
    description: master spécialisée en finance des marchés.
    from: Octobre 2017
    to: fevrier 2019



# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - r-project
  - github
  - google-drive
  - slack
  - discord
  - docker
  - markdown
  - html5
  - css3-alt
  - bootstrap
 
extra_skills:
  - Web scraping and web automation
  - Machine learning and deep learning
  - Many Python packages - Flask, NumPy, matplotlib, Tensorflow,Plotly,Keras API,LSTM,Bi-LSTM,Attention,seq2seq etc.